name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - run: elm make && elm-format --validate src
